import {
  ArrowRight,
  BadgeDollarSign,
  Ban,
  BarChart3,
  BookOpen,
  Boxes,
  Building2,
  ChartLine,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  Crosshair,
  Database,
  DollarSign,
  Factory,
  FileText,
  GitBranch,
  Globe,
  Goal,
  GraduationCap,
  Handshake,
  Info,
  Landmark,
  Laptop,
  Layers,
  Library,
  Lightbulb,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Monitor,
  Network,
  NotebookPen,
  Phone,
  PieChart,
  Presentation,
  Puzzle,
  Quote,
  Scale,
  Search,
  Share2,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TriangleAlert,
  TrendingDown,
  TrendingUp,
  Truck,
  UserRound,
  Users,
  Wallet,
  Wifi,
  WifiOff,
  type LucideIcon,
} from 'lucide-react'

export const SLIDE_ICONS = {
  TriangleAlert,
  CircleAlert,
  CircleHelp,
  CircleCheck,
  Ban,
  Info,
  Target,
  Goal,
  Crosshair,
  Search,
  BookOpen,
  GraduationCap,
  Library,
  Users,
  UserRound,
  Building2,
  Handshake,
  Landmark,
  Factory,
  Store,
  Laptop,
  Monitor,
  Smartphone,
  Wifi,
  WifiOff,
  Database,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  ChartLine,
  Lightbulb,
  Scale,
  Shield,
  ShieldCheck,
  Lock,
  FileText,
  ClipboardList,
  ListChecks,
  NotebookPen,
  Globe,
  Map,
  MapPin,
  Network,
  Share2,
  DollarSign,
  Wallet,
  BadgeDollarSign,
  Layers,
  Boxes,
  Puzzle,
  GitBranch,
  Presentation,
  Mic,
  MessageCircle,
  Quote,
  ArrowRight,
  Sparkles,
  Truck,
  Mail,
  Phone,
} as const satisfies Record<string, LucideIcon>

export type SlideIconName = keyof typeof SLIDE_ICONS

export const SLIDE_ICON_OPTIONS: { name: SlideIconName; label: string }[] = [
  { name: 'TriangleAlert', label: 'Warning' },
  { name: 'CircleAlert', label: 'Alert' },
  { name: 'CircleHelp', label: 'Question' },
  { name: 'CircleCheck', label: 'Check' },
  { name: 'Ban', label: 'Block' },
  { name: 'Info', label: 'Info' },
  { name: 'Target', label: 'Target' },
  { name: 'Goal', label: 'Goal' },
  { name: 'Crosshair', label: 'Focus' },
  { name: 'Search', label: 'Search' },
  { name: 'BookOpen', label: 'Book' },
  { name: 'GraduationCap', label: 'Graduation' },
  { name: 'Library', label: 'Library' },
  { name: 'Users', label: 'People' },
  { name: 'UserRound', label: 'Person' },
  { name: 'Building2', label: 'Organization' },
  { name: 'Handshake', label: 'Partnership' },
  { name: 'Landmark', label: 'Institution' },
  { name: 'Factory', label: 'Industry' },
  { name: 'Store', label: 'Market' },
  { name: 'Laptop', label: 'Technology' },
  { name: 'Monitor', label: 'Computer' },
  { name: 'Smartphone', label: 'Mobile' },
  { name: 'Wifi', label: 'Connected' },
  { name: 'WifiOff', label: 'Offline' },
  { name: 'Database', label: 'Data' },
  { name: 'TrendingUp', label: 'Growth' },
  { name: 'TrendingDown', label: 'Decline' },
  { name: 'BarChart3', label: 'Bar chart' },
  { name: 'PieChart', label: 'Pie chart' },
  { name: 'ChartLine', label: 'Line chart' },
  { name: 'Lightbulb', label: 'Idea' },
  { name: 'Scale', label: 'Balance' },
  { name: 'Shield', label: 'Ethics' },
  { name: 'ShieldCheck', label: 'Trust' },
  { name: 'Lock', label: 'Privacy' },
  { name: 'FileText', label: 'Document' },
  { name: 'ClipboardList', label: 'List' },
  { name: 'ListChecks', label: 'Checklist' },
  { name: 'NotebookPen', label: 'Notes' },
  { name: 'Globe', label: 'Global' },
  { name: 'Map', label: 'Map' },
  { name: 'MapPin', label: 'Location' },
  { name: 'Network', label: 'Network' },
  { name: 'Share2', label: 'Share' },
  { name: 'DollarSign', label: 'Finance' },
  { name: 'Wallet', label: 'Revenue' },
  { name: 'BadgeDollarSign', label: 'Value' },
  { name: 'Layers', label: 'Layers' },
  { name: 'Boxes', label: 'Framework' },
  { name: 'Puzzle', label: 'Gap' },
  { name: 'GitBranch', label: 'Process' },
  { name: 'Presentation', label: 'Presentation' },
  { name: 'Mic', label: 'Speak' },
  { name: 'MessageCircle', label: 'Discussion' },
  { name: 'Quote', label: 'Quote' },
  { name: 'ArrowRight', label: 'Next' },
  { name: 'Sparkles', label: 'Insight' },
  { name: 'Truck', label: 'Logistics' },
  { name: 'Mail', label: 'Email' },
  { name: 'Phone', label: 'Phone' },
]

export function isSlideIconName(name: string): name is SlideIconName {
  return name in SLIDE_ICONS
}

export function getSlideIcon(name?: string | null): LucideIcon | null {
  if (!name || !isSlideIconName(name)) return null
  return SLIDE_ICONS[name]
}

const BULLET_ICON_RE = /^\[([A-Za-z0-9]+)\]\s*(.*)$/

export function parseBulletItem(item: string): {
  icon?: SlideIconName
  text: string
} {
  const match = item.match(BULLET_ICON_RE)
  if (match && isSlideIconName(match[1])) {
    return { icon: match[1], text: match[2] }
  }
  return { text: item }
}
